## Basic Configuration
baseurl = "https://nirantk.com/"
relativeURLs = true
uglyURLs = true
languageCode = "en"

title = "Nirant Kasliwal"
theme = ["ananke"] 
Paginate = 30

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      autoHeadingID = true
      autoHeadingIDType = "github"
      [markup.goldmark.parser.attribute]
        block = false
        title = true
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false

[params]
  # body_classes = "avenir bg-near-white"
  post_content_classes = "avenir"
  # background_color_class = "bg-black"
  favicon=""
  linkedin="https://www.linkedin.com/in/nirant"
  twitter = "https://twitter.com/@NirantK"
  github="https://github.com/NirantK"
  recent_posts_number = 9

pygmentsUseClassic=true
pygmentsUseClasses=true
relatedPosts = true
postNavigation = true

[[menu.main]]
name = "about"
identifier = "about"
url = "/about"

[[menu.main]]
name = "nlp book"
identifier = "book"
url = "http://amzn.to/3i2X0jv"

[[menu.main]]
name = "community"
identifier = "community"
url = "/ai"


[[menu.main]]
name = "writing"
identifier = "writing"
url = "/writing"

[[menu.main]]
name = "substack"
identifier = "substack"
url = "https://niranting.substack.com/"

[[menu.main]]
name = "home"
identifier = "home"
url = "/"
